### ISSUE TITLE
Rotation direction

### ISSUE THREAD

**Issue by steffex** [BalestraPatrick/ParticlesLoadingView#1]
It would be nice to have a setting to change the rotation of the particle animation to clockwise.

**Comment by BalestraPatrick** [comment]
Yes, it would definitely be a nice feature to have. If you find the time, PRs are welcome! :)

**Comment by BalestraPatrick** [comment]
Fixed in 48d8dc6!

**Comment by steffex** [comment]
nice @BalestraPatrick, i had the same idea 😉
