### ISSUE TITLE
could not find file

### ISSUE THREAD

**Issue by chashmeetsingh** [BalestraPatrick/ParticlesLoadingView#2]
# fatal error: Could not find the particles file: file /Users/.../XcodeProjects/...../Pods/ParticlesLoadingView/Pod/Classes/ParticlesLoadingView.swift, line 80

(lldb)  @BalestraPatrick

**Comment by chashmeetsingh** [comment]
on investigating more

`
Error info: EmitterNodeUnavailable
Error info: EmitterNodeUnavailable
fatal error: unexpectedly found nil while unwrapping an Optional value
`

@BalestraPatrick

**Comment by BalestraPatrick** [comment]
Hello, may I know how did you install it? Did you use CocoaPods? Can you please paste here your code?

The error happens when the .sks file can't be found in the bundle. If you are using a custom one, please let me know where it is located in your project.

**Comment by chashmeetsingh** [comment]
I used cocoapods and didn't use any custom for loading will post the code in a moment 
Thanks for replying !

**Comment by chashmeetsingh** [comment]
https://gist.github.com/chashmeetsingh/21e48123031006f1c2fc0d7714fa7257 
here it is
@BalestraPatrick

**Comment by BalestraPatrick** [comment]
@chashmeetsingh Hey! Thanks for the bug report. I have located the issue and think I have fixed the it with the last commit b485156. Can you please run a `pod install` and let me know if the new version fixed the issue?

**Comment by chashmeetsingh** [comment]
nope

SKTexture: Error loading image resource: "spark"

**Comment by BalestraPatrick** [comment]
That message appears because the particles file is trying to look for the image in the wrong directory. I fixed the issue by reassigning the correct file path by code. Unfortunately to remove that message from the console, I would have to remove the image from the particles editor but that would prevent the debugging and designing of the particles animation in the Xcode editor. Does the animation work correctly now?

**Comment by chashmeetsingh** [comment]
nope still 
2016-05-29 22:43:36.698 TMS-iOS[3826:87571] SKTexture: Error loading image resource: "spark"
fatal error: Could not find the particles file: file /Users/...../XcodeProjects/..../Pods/ParticlesLoadingView/Pod/Classes/ParticlesLoadingView.swift, line 80

**Comment by chashmeetsingh** [comment]
also is it possible to add custom text inside the loaders or around it ? @BalestraPatrick

**Comment by BalestraPatrick** [comment]
I only see the warning message in my console in a new empty project that uses CocoaPods. Everything else works fine here. Can you share more details about your setup or maybe try a new empty project? 

Regarding the text yes, it's possible. Take a look at the example project. You could create your own `UIView` class with your text and so on. Then add the animation via the `addParticlesAnimation:`.

**Comment by chashmeetsingh** [comment]
checking again

**Comment by chashmeetsingh** [comment]
not working  @BalestraPatrick 
Sample project link https://github.com/chashmeetsingh/particleLoadingViewTest

**Comment by BalestraPatrick** [comment]
Thanks a lot for the useful sample project! I just pushed a new version which should finally fix the issue.
Bundle directories are hard sometimes 😉

**Comment by chashmeetsingh** [comment]
awesome thanks :) finally works 👍

**Comment by chashmeetsingh** [comment]
removing logs?

**Comment by BalestraPatrick** [comment]
That message is not under my control. It's a warning message printed by the `SpriteKit` framework. I will try and see if it's possible to remove it.

**Comment by chashmeetsingh** [comment]
[SKTexture](https://github.com/BalestraPatrick/ParticlesLoadingView/blob/335ee3f98ac71874f40757c668a43ebeca48bd9a/Pod/Classes/EmitterCreator.swift#L28) here null is set, thats why that log message @BalestraPatrick
