### ISSUE TITLE
Errors for Pod Suggest old version of swift

### ISSUE THREAD

**Issue by stevensanborn** [BalestraPatrick/ParticlesLoadingView#3]
pod 'ParticlesLoadingView'

looks like code needs to be upgraded to latest version of swift

" 'ErrorType' has been renamed to 'Error'"
 'EmitterCreator.EmitterError' does not conform to protocol 'RawRepresentable'

'willMoveToSuperview' has been renamed to 'willMove(toSuperview:)'
....

**Comment by BalestraPatrick** [comment]
@stevensanborn Sorry about that, I didn't push the 0.4 tag to the Specs repo. Please run `pod update` in your project and it should now work as expected.
