### ISSUE TITLE
adding loading particles to my view disables user interaction

### ISSUE THREAD

**Issue by omaarr90** [BalestraPatrick/ParticlesLoadingView#4]

**Comment by BalestraPatrick** [comment]
Hey @omaarr90! Can you please provide some example code that you're using in order to debug and fix this issue?

**Comment by omaarr90** [comment]
I'm not doing anything. I'm using SVPinView which consists of a collection view of text fields. 

```
        self.pinView.addParticlesAnimation(with: pinEmitter)
```

after adding this line. I was unable to click the text fields.

I solved it by the following code:
```
        spriteKitView.isUserInteractionEnabled = false
```

in `public func addParticlesAnimation(with emitter: SKEmitterNode? = nil, effect: ParticleEffect? = nil)`
