### ISSUE TITLE
"Overriding non-@objc declarations from extensions is not supported"

### ISSUE THREAD

**Issue by johnlietzke** [BalestraPatrick/ParticlesLoadingView#5]
"Overriding non-@objc declarations from extensions is not supported"

I get this error when I try to compile in Swift 4.1, Xcode 9.4.

**Comment by BalestraPatrick** [comment]
Hey @johnlietzke, you are probably pointing your podspec to master. If you are using Swift 4, you were supposed to point your Podspec to the `swift4` branch. No worries, the `master`  branch now contains the Swift 4 support, so please just run `pod install` and it should be fixed!

**Comment by johnlietzke** [comment]
Patrick, I was unable to get it work using pod install.  Same issue.

**Comment by BalestraPatrick** [comment]
@johnlietzke Did you run also `pod update`? Please post here your Podfile if you need more help.

**Comment by johnlietzke** [comment]
Thank for the fast response and quick fix..  That worked. I feel rather dumb.  

Best,

John
